CREATE TYPE USER_ROLE AS ENUM('Customer', 'Seller', 'Administrator');

CREATE TYPE ORDER_STATUS AS ENUM(
	'Pending',
	'Processing',
	'Shipped',
	'Delivered',
	'Cancelled'
);

CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORDHASH VARCHAR(255) NOT NULL,
	PHONENUMBER VARCHAR(20),
	ROLE USER_ROLE NOT NULL DEFAULT 'Customer',
	CREATEDAT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE SELLERS (
	ID SERIAL PRIMARY KEY,
	USERID INT NOT NULL UNIQUE,
	STORENAME VARCHAR(200) NOT NULL,
	DESCRIPTION TEXT,
	CONSTRAINT FK_SELLERS_USERS FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE CATEGORIES (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL UNIQUE,
	DESCRIPTION TEXT
);

CREATE TABLE PRODUCTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL,
	DESCRIPTION TEXT,
	PRICE DECIMAL(18, 2) NOT NULL CHECK (PRICE >= 0),
	STOCKQUANTITY INT NOT NULL DEFAULT 0 CHECK (STOCKQUANTITY >= 0),
	MAINIMAGEURL VARCHAR(500),
	CATEGORYID INT NOT NULL,
	SELLERID INT NOT NULL,
	ISACTIVE BOOLEAN DEFAULT TRUE,
	CREATEDAT TIMESTAMP DEFAULT NOW(),
	CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (ID) ON DELETE RESTRICT,
	CONSTRAINT FK_PRODUCTS_SELLERS FOREIGN KEY (SELLERID) REFERENCES SELLERS (ID) ON DELETE CASCADE
);

CREATE TABLE PRODUCTIMAGES (
	ID SERIAL PRIMARY KEY,
	PRODUCTID INT NOT NULL,
	IMAGEURL VARCHAR(500) NOT NULL,
	SORTORDER INT DEFAULT 0,
	CONSTRAINT FK_PRODUCTIMAGES_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE
);

CREATE TABLE CARTITEMS (
	ID SERIAL PRIMARY KEY,
	USERID INT NOT NULL,
	PRODUCTID INT NOT NULL,
	QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
	ADDEDAT TIMESTAMP DEFAULT NOW(),
	CONSTRAINT FK_CARTITEMS_USERS FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE CASCADE,
	CONSTRAINT FK_CARTITEMS_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE
);

CREATE TABLE ORDERS (
	ID SERIAL PRIMARY KEY,
	USERID INT NOT NULL,
	ORDERDATE TIMESTAMP DEFAULT NOW(),
	TOTALAMOUNT DECIMAL(18, 2) NOT NULL CHECK (TOTALAMOUNT >= 0),
	STATUS ORDER_STATUS NOT NULL DEFAULT 'Pending',
	SHIPPINGADDRESS TEXT NOT NULL,
	CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USERID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE ORDERITEMS (
	ID SERIAL PRIMARY KEY,
	ORDERID INT NOT NULL,
	PRODUCTID INT,
	PRODUCTNAME VARCHAR(200) NOT NULL,
	PRICE DECIMAL(18, 2) NOT NULL,
	QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
	CONSTRAINT FK_ORDERITEMS_ORDERS FOREIGN KEY (ORDERID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
	CONSTRAINT FK_ORDERITEMS_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS (ID) ON DELETE SET NULL
);

CREATE INDEX IX_PRODUCTS_CATEGORYID ON PRODUCTS (CATEGORYID);

CREATE INDEX IX_PRODUCTS_SELLERID ON PRODUCTS (SELLERID);

CREATE INDEX IX_CARTITEMS_USERID ON CARTITEMS (USERID);

CREATE INDEX IX_ORDERS_USERID ON ORDERS (USERID);

CREATE INDEX IX_ORDERITEMS_ORDERID ON ORDERITEMS (ORDERID);

ALTER TABLE USERS
ALTER COLUMN ROLE TYPE TEXT;